[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "chmod on selected files"

[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'

[[mgr.prepend_keymap]]
on   = "<C-n>"
run  = 'shell --confirm -- ripdrag "$@" -x 2>/dev/null &'

[[mgr.prepend_keymap]]
on   = [ "g", "r" ]
run  = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "back to the root of the current git repository"

[[mgr.prepend_keymap]]
on   = "<C-t>"
run  = "plugin toggle-pane min-preview"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"

[[mgr.prepend_keymap]]
on   = "b"
run  = 'shell -- swww img "$0"'

[[mgr.prepend_keymap]]
on   = "C"
run  = "plugin ouch"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = [ "L" ]
run = "plugin bypass"

[[mgr.prepend_keymap]]
on = [ "H" ]
run = "plugin bypass reverse"
