---
gui:
    scrollHeight: 4
    scrollPastBottom: true

    mouseEvents: false

    sidePanelWidth: 0.25
    expandFocusedSidePanel: true
    expandedSidePanelWeight: 2
    mainPanelSplitMode: flexible
    enlargedSideViewLocation: top

    timeFormat: 2006-01-02 (Mon, Jan 01)
    shortTimeFormat: 15:04

    nerdFontsVersion: 3
    showFileIcons: true

    screenMode: half
    splitDiff: auto
    border: hidden
    portraitMode: auto

    filterMode: fuzzy

git:
    paging:
        colorArg: always
        pager: delta --paging=never
