[manager]
ratio = [1, 3, 3]
sort_by = "natural"
sort_dir_first = true
sort_translit = true
linemode = "none"
show_symlink = true
scrolloff = 5

[preview]
wrap = "yes"
tab_size = 4
max_width = 1280
max_height = 720

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
